name: deployment 
on: push 
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Find code
              uses: actions/checkout@v3
            # - name: Install Node
            #   uses: actions/setup-node@v5
            #   with:
            #     node-version: 18 
            - name: Install dependencies
              uses: npm ci
            - name: Run lint
              uses: npm run lint
    test:
        needs: lint
        runs-on: ubuntu-latest
        steps:
            - name: Run test
              uses: npm test
    deploy: 
        needs: test
        runs-on: ubuntu-latest
        steps:
            - name: Build code
              uses: npm run build
            - name: Deploy code
              uses: echo "Deploying code"

